### PR TITLE
Download polyfills only if necessary

### PR DESCRIPTION
**Pull request by k1sul1**

### CODE REVIEW

**Comment by anttiviljami** [comment]
I'm getting this error when using this branch. The form doesn't submit properly either.

screen shot 2017-10-02 at 23 05 24

**Comment by anttiviljami** [comment]
script is still not initialising the form. the script is included on the page but submit falls back to a GET request

**Comment by anttiviljami** [comment]
I'm not really following the logic of your dependency loader. It seems to only initalize if all dependencies are loaded via polyfills.

**Comment by anttiviljami** [comment]
Shouldn't you increment dependencies_loaded in the else block here? https://github.com/anttiviljami/wp-libre-form/pull/76/files#diff-8554cc24257276c75d5d599331aa60b2R126

**Comment by k1sul1** [comment]
This PR is a mess :D I took most of the code that I wrote back in January for #48 and changed it a "bit". Back then `dependencies` was empty if you didn't need any dependencies, now it has two values and `dependencies_loaded` is obviously broken. 

I'll clean this branch up and submit another.

**Pull request closed without merging**
