### PR TITLE
Allow enqueueing the script by registering it outside the if-clause + readme mentions

### PR DESCRIPTION
**Pull request by k1sul1**
As the title states. I had some _minor_ issues with vim, so sorry if there are any surprises within the readme.

### CODE REVIEW

**Comment by anttiviljami** [comment]
Could you add your email address to your committer ID please so you can be a contributor in the commit log? :)

**Comment by anttiviljami** [comment]
Otherwise looks great ! Thanks for the PR

**Comment by k1sul1** [comment]
Nice catch. Work email :)

**Comment by anttiviljami** [comment]
:+1:

**Pull request merged**
