### PR TITLE
Moved wplf form initialization under window.wplf.attach

### PR DESCRIPTION
**Pull request by jpeltoniemi**

### CODE REVIEW

**Comment by anttiviljami** [comment]
Looks fine to me. What's the rationale behind this?

**Comment by anttiviljami** [comment]
Thanks for the PR btw! 😊 👍

**Comment by jpeltoniemi** [comment]
I thought I needed to attach Libre Form to a dynamically generated form. Didn't really think it through and just made the changes before deciding if it is actually needed. But it seems to work and should open up more possibilities for other use cases, so why not 😄

**Comment by anttiviljami** [comment]
Ok cool. I see no reason why not to do this. I guess it's good to have a way to dynamically call `window.wplf.attach` :+1:

Merging!

**Pull request merged**
