### PR TITLE
Add multilingual support for success messages

### PR DESCRIPTION
**Pull request by k1sul1**
Originally shipped without because it was supposed to be hard.
It wasn't.

### CODE REVIEW

**Comment by k1sul1** [comment]
@anttiviljami what do you think?

Are the filter names ok or does anyone have better ideas?

**Comment by k1sul1** [comment]
One thing; class.wplf-polylang.php is quite repetitive, could we do something about that in the near future?

**Comment by anttiviljami** [comment]
I get `Fatal error: Uncaught Error: Call to undefined function pll_current_language()` after applying this patch without polylang. 

Fix pls. :)

Otherwise looks great!

**Comment by anttiviljami** [comment]
Also, might want to make sure the call to pll_current_language() comes after the `plugins_loaded` hook. wp-libre-form might get loaded before and this will cause a 500 fatal error

**Comment by k1sul1** [comment]
👍 I'll look into this tomorrow.

**Comment by k1sul1** [comment]
`pll_current_language()` is called just before `wp_localize_script()`; it should work as is. 

If I check that Polylang exists before instantiating the class the fatal should be gone.

**Comment by k1sul1** [comment]
Could we use Travis to test that the plugin works with and without Polylang?

**Comment by anttiviljami** [comment]
We could. I'll gladly accept a PR for a test like that.

**Comment by k1sul1** [comment]
😁 Not my strong suite, but maybe. 

Did you notice that the Travis build errors are not even related to commit? Previous commit build succeeded, and the next commit is one line: https://github.com/anttiviljami/wp-libre-form/pull/72/commits/a76d1a8df263e5014defe9e3562d462b2afa20b2

**Comment by anttiviljami** [comment]
Must be a wpcs update. Don't worry about it. Need to fix in master so you can rebase

**Comment by anttiviljami** [comment]
Should be fixed now. Please rebase to master and push to run travis again for this PR

**Comment by k1sul1** [comment]
That was harder than expected but should be fine now.

**Pull request merged**
