### PR TITLE
File upload features

### PR DESCRIPTION
**Pull request by k1sul1**
I added the attachment url as suggested in https://github.com/anttiviljami/wp-libre-form/pull/7#issuecomment-233261448.

Also includes form filter (#11) and client side callbacks on form submit.

### CODE REVIEW

**Comment by k1sul1** [comment]
image

Here it is in action. I'm not entirely happy about the fact that there is still no full url, but I'm not exactly fond of saving full urls to database either. 

Maybe we shouldn't save the attachment url / path in the database at all, but instead get it while displaying the submission?

**Comment by anttiviljami** [comment]
That looks loads better !

**Comment by anttiviljami** [comment]
I still kind of think it would be cool to have a clickable link to the file in the table UI. Maybe a link after the key `kuva1` name? 

Sort of like

```
kuva1 [link](link_to_file)
kuva1_attachment [link](link_to_attachment)
```

**Comment by k1sul1** [comment]
Clickable links added, as requested. 

One direct, and one to the attachment page in wp-admin.

**Comment by onnimonni** [comment]
Would it be possible to add a check if the file is bigger than
```
$limit = apply_filters('upload_size_limit');
```
in the frontend javascript?

This is what wordpress already does in the wp-admin.

**Comment by k1sul1** [comment]
@onnimonni Yes it should be. Just pass it using `wp_localize_script`. 

The actual size check is rather trivial, just one Google search away.

**Pull request merged**
