### PR TITLE
Add basic support for file uploads

### PR DESCRIPTION
**Pull request by k1sul1**
I was bored and I need the support for file uploads pretty soon, so I added it.

Because $.post is unable to send files, I ditched jQuery and used fetch instead. Necessary polyfills (fetch & promises) are included on the top of wplf-form.js, but this still needs some testing. I was able to succesfully submit a form and receive the thank you message, but IE, Edge, Firefox & Safari are currenly untested. 

Everything should work out of the box, but it never hurts to be careful.

### CODE REVIEW

**Comment by anttiviljami** [comment]
Great work ! I've created a new branch for this feature. I don't think it's quite finished yet. Making some improvements right now.

https://github.com/anttiviljami/wp-libre-form/pull/8

**Comment by k1sul1** [comment]
Agreed, it needs some work. if you got anything in mind that I could help with, just holler and I'll try to find the time for it :)

**Comment by anttiviljami** [comment]
Right now it just writes the attachment post id in the custom field. For a better user experience, I would suggest we save the url to the uploaded file as one meta field and the attachment id as another. Maybe something like

<fieldname> => https://mysite.com/wp-content/uploads/2016/07/uploaded.png
<fieldname>_attachment => 123

**Comment by anttiviljami** [comment]
I feel like it's easier for most users just to save the link to the file, instead of looking for the attachment id in the media library.

**Comment by k1sul1** [comment]
I agree, and I was going to open an issue about it, as just showing the attachment ID doesn't make any sense. But what happens when uploading multiple files through same file input? 

Currently you can't do that, but implementing it should be easy.

**Pull request closed without merging**
